SET SERVEROUTPUT ON
SET VERIFY OFF

SELECT * FROM DD_CLIENT;

ACCEPT NUMCLIENT_OLD PROMPT "Entrez l''ancien numero de client: "
ACCEPT NUMCLIENT_NEW PROMPT "Entrez le nouveau numero de client: "

DECLARE
	TABLE_EXISTE_PAS EXCEPTION;
	NB NUMBER(1) := 0;
BEGIN
	SELECT COUNT(NUMCLIENT) INTO NB FROM DD_CLIENT WHERE NUMCLIENT = '&NUMCLIENT_OLD';
	IF NB > 0 THEN
		UPDATE DD_CLIENT
		  SET NUMCLIENT = '&NUMCLIENT_NEW' WHERE NUMCLIENT = '&NUMCLIENT_OLD';		
	ELSE
		RAISE TABLE_EXISTE_PAS;	
	END IF;	
EXCEPTION 
	WHEN TABLE_EXISTE_PAS THEN
	DBMS_OUTPUT.PUT_LINE('Le numero de client n''existe pas dans la table venteclient');
END;
/
SET VERIFY ON


PROMPT Appuyer sut une touche ...
PAUSE
@C:\Users\usager\Desktop\base\PROJET_FINAL2\MENU.sql