SET SERVEROUTPUT ON
DECLARE

NB NUMBER(1) := 0;

BEGIN
		SELECT COUNT(TABLE_NAME) INTO NB FROM TABS WHERE TABLE_NAME = 'DD_PRODUITSUPPRIMES';
		IF NB > 0 THEN
		DBMS_OUTPUT.PUT_LINE('La table PRODUITSUPPRIMES existe deja!');
	ELSE
		EXECUTE IMMEDIATE 'CREATE TABLE DD_PRODUITSUPPRIMES (
					NUMPROD CHAR(7), 
					NOM VARCHAR2(50),
					NUMCAT VARCHAR2(20))';
	END IF;
	
END;
/