CREATE OR REPLACE PACKAGE BODY TAXEPACKAGE AS 

FUNCTION COUTVENTE(QUANTITE_VENDU IN NUMBER, PRIX_VENTE IN NUMBER) 
RETURN NUMBER IS
COUT NUMBER;

BEGIN
	COUT := QUANTITE_VENDU * PRIX_VENTE;
	RETURN (COUT);
END COUTVENTE;

FUNCTION TAXE(COUT IN number) 
RETURN NUMBER IS
TAXE NUMBER;

BEGIN
	TAXE := COUT*0.15;
	RETURN (TAXE);
END TAXE;

END TAXEPACKAGE;
/